import { useState, useCallback, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  GraduationCap, Shield, Users, BookOpen, Award, RefreshCw,
  CheckCircle, UserPlus, LogOut, FileText, ChevronDown, ChevronUp,
  ClipboardList, X,
} from "lucide-react";
import {
  useSynchroStore, totalScore,
  type OffenderRecord,
} from "@/shared/stores/synchroStore";
import { SYNCHRO_MODULES } from "@/features/synchrolearn/data/modules";

// ── Utilities ─────────────────────────────────────────────────────────────────

async function sha256(input: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

function openParoleReport(off: OffenderRecord, facilitatorName: string) {
  const total = totalScore(off.scores);
  const completed = off.scores.filter((s) => s === 20).length;
  const html = `<!DOCTYPE html><html><head><title>Parole Report – ${off.name}</title>
<style>
  body{font-family:Georgia,serif;padding:48px;background:#fff8e7;color:#1a2a3a;max-width:720px;margin:0 auto;}
  h2{color:#1a3a6a;border-bottom:2px solid #c8a800;padding-bottom:8px;margin-bottom:20px;}
  .badge{display:inline-block;background:#1a3a6a;color:#fff;padding:3px 10px;border-radius:20px;font-size:.8rem;}
  .hl{color:#0055a5;font-weight:700;} p{margin:8px 0;line-height:1.6;}
  hr{border:none;border-top:1px solid #ccc;margin:24px 0;}
  .footer{font-size:.75rem;color:#777;margin-top:32px;}
  @media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact;}}
</style></head><body>
<h2>FINLIT SynchroLearn — Parole &amp; Reintegration Report</h2>
<p><strong>Offender:</strong> ${off.name} <span class="badge">${off.id}</span></p>
<p><strong>Total Score:</strong> <span class="hl">${total}/100</span> &nbsp;|&nbsp;
   <strong>Modules Completed:</strong> <span class="hl">${completed}/5</span></p>
<p><strong>Certificate Issued:</strong> ${off.certIssued ? '<span style="color:#1a7a3a">YES ✅</span>' : 'NO'}</p>
<p><strong>Facilitator:</strong> ${facilitatorName}</p>
<p><strong>Date:</strong> ${new Date().toLocaleDateString("en-ZA", { dateStyle: "long" })}</p>
<hr>
<p>✅ This offender has demonstrated understanding of crime prevention, financial literacy, and JSE market principles
through the FINLIT SynchroLearn programme. Recommended for reintegration and parole consideration.</p>
<div class="footer">Generated by FINLIT SynchroLearn — SAPS Social Crime Prevention Programme</div>
</body></html>`;
  const win = window.open("", "_blank", "width=800,height=620");
  if (win) { win.document.write(html); win.document.close(); setTimeout(() => win.print(), 400); }
}

// ── Toast system ──────────────────────────────────────────────────────────────

interface ToastItem { id: string; message: string; type: "success" | "error" | "info"; }

function useToasts() {
  const [toasts, setToasts] = useState<ToastItem[]>([]);
  const show = useCallback((message: string, type: ToastItem["type"] = "info") => {
    const id = crypto.randomUUID();
    setToasts((prev) => [...prev, { id, message, type }]);
    setTimeout(() => setToasts((prev) => prev.filter((t) => t.id !== id)), 4500);
  }, []);
  return { toasts, show };
}

function ToastContainer({ toasts }: { toasts: ToastItem[] }) {
  return (
    <div className="fixed top-6 right-6 z-[999] flex flex-col gap-3 pointer-events-none">
      <AnimatePresence>
        {toasts.map((t) => (
          <motion.div
            key={t.id}
            initial={{ opacity: 0, x: 40 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 40 }}
            className={`flex items-center gap-3 px-5 py-4 rounded-2xl text-sm font-semibold shadow-xl backdrop-blur-xl max-w-sm border ${
              t.type === "success" ? "bg-dark-card/95 border-xhosa-teal/40"
              : t.type === "error"   ? "bg-dark-card/95 border-xhosa-red/40"
              : "bg-dark-card/95 border-gold/40"
            } text-white`}
          >
            {t.type === "success" ? "✅" : t.type === "error" ? "❌" : "ℹ️"}
            {t.message}
          </motion.div>
        ))}
      </AnimatePresence>
    </div>
  );
}

// ── Confetti ──────────────────────────────────────────────────────────────────

function Confetti({ onDone }: { onDone: () => void }) {
  const COLORS = ["#D4AF37", "#F4E4A6", "#2D9C5E", "#0A4D3C", "#8B1A1A", "#1E3A5F", "#E07B39"];
  const pieces = Array.from({ length: 44 }, (_, i) => ({
    id: i,
    left: Math.random() * 100,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    delay: Math.random() * 0.6,
    size: 7 + Math.random() * 9,
  }));

  useEffect(() => {
    const t = setTimeout(onDone, 2200);
    return () => clearTimeout(t);
  }, [onDone]);

  return (
    <>
      {pieces.map((p) => (
        <motion.div
          key={p.id}
          style={{
            position: "fixed", left: `${p.left}%`, top: -24,
            width: p.size, height: p.size, borderRadius: "50%",
            background: p.color, zIndex: 998, pointerEvents: "none",
          }}
          initial={{ y: -24, opacity: 1, rotate: 0 }}
          animate={{ y: "110vh", opacity: 0, rotate: 720 }}
          transition={{ duration: 1.5 + Math.random() * 0.8, delay: p.delay, ease: "easeIn" }}
        />
      ))}
    </>
  );
}

// ── Certificate modal ─────────────────────────────────────────────────────────

interface CertData {
  offender: OffenderRecord;
  hash: string;
  certId: string;
  date: string;
  facilitatorName: string;
}

function CertificateModal({ data, onClose }: { data: CertData; onClose: () => void }) {
  const { offender, hash, certId, date, facilitatorName } = data;
  const total = totalScore(offender.scores);
  const completedMods = SYNCHRO_MODULES.filter((_, i) => offender.scores[i] === 20);

  const handlePrint = () => {
    const html = `<!DOCTYPE html><html><head><title>Certificate – ${offender.name}</title>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;800&family=Cinzel:wght@700&display=swap" rel="stylesheet">
<style>
  *{box-sizing:border-box;margin:0;padding:0;}
  body{font-family:Georgia,serif;background:#0D1117;color:#F0F3FA;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:40px;}
  .card{max-width:820px;width:100%;border:2px solid #D4AF37;border-radius:24px;padding:48px 56px;position:relative;background:linear-gradient(145deg,#0D1117,#161B22,#0D1117);}
  .brand{font-family:'Cinzel',serif;font-size:.6rem;letter-spacing:.35em;text-transform:uppercase;color:#D4AF37;text-align:center;margin-bottom:12px;}
  h1{font-family:'Playfair Display',serif;font-size:2rem;font-weight:800;text-align:center;color:#F4E4A6;margin-bottom:6px;}
  .sub{font-size:.8rem;text-align:center;letter-spacing:.12em;text-transform:uppercase;color:#6B7280;margin-bottom:24px;}
  .greeting{font-family:'Playfair Display',serif;font-style:italic;font-size:1.1rem;color:#F4E4A6;text-align:center;padding:14px;border:1px solid rgba(212,175,55,.15);border-radius:12px;margin-bottom:20px;}
  .name{font-family:'Playfair Display',serif;font-size:2.2rem;font-weight:700;text-align:center;color:#F5F0E8;margin-bottom:6px;}
  .id{font-size:.75rem;font-family:monospace;color:#D4AF37;background:rgba(212,175,55,.08);border:1px solid rgba(212,175,55,.3);padding:4px 14px;border-radius:8px;display:inline-block;margin-bottom:20px;}
  .score{font-family:'Playfair Display',serif;font-size:3.5rem;font-weight:800;color:#D4AF37;text-align:center;}
  .score-lbl{font-size:.75rem;text-align:center;letter-spacing:.12em;text-transform:uppercase;color:#6B7280;margin-bottom:20px;}
  .body{padding:20px;border:1px solid rgba(255,255,255,.06);border-radius:14px;margin-bottom:16px;text-align:center;font-size:.9rem;color:#A0A8B8;line-height:1.7;}
  .modules{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px;}
  .mod{font-size:.75rem;color:#2D9C5E;padding:8px 12px;background:rgba(45,156,94,.08);border:1px solid rgba(45,156,94,.2);border-radius:8px;text-align:left;}
  .hash-box{padding:16px;border:1px solid rgba(212,175,55,.25);border-radius:12px;margin-bottom:20px;text-align:center;}
  .hash-lbl{font-size:.65rem;font-family:monospace;color:#D4AF37;letter-spacing:.15em;text-transform:uppercase;margin-bottom:6px;}
  .hash-val{font-family:monospace;font-size:.65rem;color:#6B7280;word-break:break-all;padding:8px;background:rgba(0,0,0,.3);border-radius:6px;}
  .footer{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;border-top:1px solid rgba(212,175,55,.15);padding-top:16px;}
  .fl{font-size:.7rem;color:#6B7280;text-transform:uppercase;letter-spacing:.12em;margin-bottom:4px;}
  .fv{font-family:'Playfair Display',serif;font-size:.9rem;color:#F5F0E8;}
  hr{border:none;height:1px;background:linear-gradient(90deg,transparent,rgba(212,175,55,.3),transparent);margin:20px 0;}
  @media print{body{background:#0D1117;print-color-adjust:exact;-webkit-print-color-adjust:exact;}}
</style></head><body>
<div class="card">
  <div class="brand">Xhosa Rise Global Holdings</div>
  <h1>Certificate of Completion</h1>
  <div class="sub">FINLIT SynchroLearn Premium · SAPS Crime Prevention</div>
  <hr>
  <div class="greeting">"Wamkelekile, Mhlonitshwa, Future Wealth Builder!"</div>
  <p style="text-align:center;font-size:.75rem;color:#6B7280;letter-spacing:.2em;text-transform:uppercase;margin-bottom:8px;">This certifies that</p>
  <div class="name">${offender.name}</div>
  <div style="text-align:center;margin-bottom:16px;"><span class="id">${offender.id}</span></div>
  <div class="score">${total}/100</div>
  <div class="score-lbl">Total Points Earned</div>
  <div class="body">
    Has successfully completed the <strong style="color:#F4E4A6;">FINLIT SynchroLearn Premium</strong> programme,
    demonstrating mastery in crime prevention, financial literacy, and JSE market education.
    <div class="modules">
      ${completedMods.map((m) => `<div class="mod">✅ ${m.name}</div>`).join("")}
    </div>
  </div>
  <div class="hash-box">
    <div class="hash-lbl">🔐 Blockchain Verified · Unique Certificate Hash</div>
    <div class="hash-val">${hash}</div>
    <div style="font-size:.7rem;color:#2D9C5E;margin-top:8px;font-family:monospace;">✅ Verified on FINLIT Chain · Immutable Record</div>
  </div>
  <div class="footer">
    <div><div class="fl">Facilitator</div><div class="fv">${facilitatorName}</div></div>
    <div><div class="fl">Date Issued</div><div class="fv">${date}</div></div>
    <div><div class="fl">Certificate ID</div><div class="fv">${certId}</div></div>
  </div>
</div>
</body></html>`;
    const win = window.open("", "_blank", "width=1050,height=800");
    if (win) { win.document.write(html); win.document.close(); setTimeout(() => win.print(), 500); }
  };

  return (
    <motion.div
      className="fixed inset-0 z-[200] flex items-start md:items-center justify-center p-4 overflow-y-auto"
      style={{ background: "rgba(13,17,23,0.96)", backdropFilter: "blur(20px)" }}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <motion.div
        className="relative w-full max-w-3xl my-8 rounded-3xl overflow-hidden"
        style={{
          background: "linear-gradient(145deg,#0D1117 0%,#161B22 50%,#0D1117 100%)",
          border: "2px solid #D4AF37",
          boxShadow: "0 0 60px rgba(212,175,55,.15), 0 20px 60px rgba(0,0,0,.5)",
        }}
        initial={{ y: 60, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ type: "spring", stiffness: 280, damping: 24 }}
      >
        {/* Shimmer bars */}
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 4, background: "linear-gradient(90deg,transparent,#D4AF37,#F4E4A6,#D4AF37,transparent)" }} />
        <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: 4, background: "linear-gradient(90deg,transparent,#D4AF37,#F4E4A6,#D4AF37,transparent)" }} />

        {/* Corner decorations */}
        {([
          { top: 16, left: 16, borderRight: "none", borderBottom: "none" },
          { top: 16, right: 16, borderLeft: "none", borderBottom: "none" },
          { bottom: 16, left: 16, borderRight: "none", borderTop: "none" },
          { bottom: 16, right: 16, borderLeft: "none", borderTop: "none" },
        ] as React.CSSProperties[]).map((s, i) => (
          <div key={i} style={{ position: "absolute", width: 44, height: 44, border: "2px solid #D4AF37", opacity: 0.5, ...s }} />
        ))}

        {/* Close */}
        <button type="button" onClick={onClose} aria-label="Close certificate"
          className="absolute top-5 right-5 z-10 text-muted-foreground hover:text-white transition-colors">
          <X className="w-5 h-5" />
        </button>

        {/* Content */}
        <div className="px-8 md:px-14 py-12 relative z-[1]">
          {/* Header */}
          <div className="text-center mb-7 pb-6" style={{ borderBottom: "1px solid rgba(212,175,55,.2)" }}>
            <p className="font-mono text-[10px] font-bold tracking-[0.35em] uppercase text-gold mb-3">
              Xhosa Rise Global Holdings
            </p>
            <h2 className="font-serif text-3xl md:text-4xl font-bold mb-2"
              style={{ background: "linear-gradient(135deg,#F5F0E8,#F4E4A6,#D4AF37)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>
              Certificate of Completion
            </h2>
            <p className="text-[11px] tracking-[0.15em] uppercase text-muted-foreground">
              FINLIT SynchroLearn Premium · SAPS Crime Prevention
            </p>
          </div>

          {/* Xhosa greeting */}
          <div className="text-center mb-5 px-4 py-4 rounded-2xl"
            style={{ background: "rgba(212,175,55,.05)", border: "1px solid rgba(212,175,55,.15)" }}>
            <p className="font-serif italic text-lg md:text-xl" style={{ color: "#F4E4A6" }}>
              "Wamkelekile, Mhlonitshwa, Future Wealth Builder!"
            </p>
          </div>

          {/* Seal */}
          <div className="flex justify-center mb-4">
            <div className="w-16 h-16 rounded-full flex items-center justify-center text-2xl"
              style={{ background: "linear-gradient(135deg,#B8960C,#D4AF37)", boxShadow: "0 0 30px rgba(212,175,55,.35)" }}>
              🏆
            </div>
          </div>

          {/* Recipient */}
          <div className="text-center mb-5">
            <p className="text-[11px] text-muted-foreground uppercase tracking-[0.2em] mb-2">This certifies that</p>
            <p className="font-serif text-3xl font-bold text-white mb-2">{offender.name}</p>
            <span className="inline-block font-mono text-xs text-gold px-4 py-1.5 rounded-lg"
              style={{ background: "rgba(212,175,55,.08)", border: "1px solid rgba(212,175,55,.3)" }}>
              {offender.id}
            </span>
          </div>

          {/* Score */}
          <div className="text-center mb-5">
            <p className="font-serif text-5xl font-black"
              style={{ background: "linear-gradient(135deg,#D4AF37,#F4E4A6)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>
              {total}/100
            </p>
            <p className="text-[11px] text-muted-foreground uppercase tracking-[0.15em] mt-1">Total Points Earned</p>
          </div>

          {/* Body + module list */}
          <div className="mb-5 px-4 py-5 rounded-2xl text-center"
            style={{ background: "rgba(255,255,255,.02)", border: "1px solid rgba(255,255,255,.06)" }}>
            <p className="text-sm text-white/70 leading-relaxed max-w-lg mx-auto">
              Has successfully completed the <strong className="text-gold/90">FINLIT SynchroLearn Premium</strong> programme,
              demonstrating mastery in crime prevention, financial literacy, and JSE market education.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-4 text-left">
              {completedMods.map((mod, i) => (
                <div key={i} className="flex items-start gap-2 px-3 py-2 rounded-xl text-xs"
                  style={{ background: "rgba(45,156,94,.08)", border: "1px solid rgba(45,156,94,.2)", color: "#2D9C5E" }}>
                  <span className="shrink-0">✅</span> {mod.name}
                </div>
              ))}
            </div>
          </div>

          {/* Blockchain hash */}
          <div className="mb-5 p-4 rounded-2xl text-center"
            style={{ background: "linear-gradient(145deg,rgba(0,0,0,.4),rgba(22,27,34,.6))", border: "1px solid rgba(212,175,55,.25)" }}>
            <p className="font-mono text-[10px] text-gold uppercase tracking-[0.2em] mb-2">
              🔐 Blockchain Verified · Unique Certificate Hash
            </p>
            <p className="font-mono text-[10px] text-white/45 break-all p-3 rounded-lg"
              style={{ background: "rgba(0,0,0,.3)", border: "1px dashed rgba(212,175,55,.3)", letterSpacing: "0.04em" }}>
              {hash}
            </p>
            <p className="font-mono text-[10px] mt-2" style={{ color: "#2D9C5E" }}>
              ✅ Verified on FINLIT Chain · Immutable Record
            </p>
          </div>

          {/* Footer row */}
          <div className="grid grid-cols-3 gap-3 pt-5"
            style={{ borderTop: "1px solid rgba(212,175,55,.15)" }}>
            {[
              { label: "Facilitator", value: facilitatorName },
              { label: "Date Issued",  value: date },
              { label: "Certificate ID", value: certId },
            ].map(({ label, value }) => (
              <div key={label} className="text-center">
                <p className="text-[10px] text-muted-foreground uppercase tracking-[0.15em] mb-1">{label}</p>
                <p className="font-serif text-sm font-semibold text-white truncate">{value}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="text-center pb-8 flex flex-wrap justify-center gap-3 px-6">
          <button type="button" className="btn-premium flex items-center gap-2 px-8" onClick={handlePrint}>
            🖨️ Print Certificate
          </button>
          <button type="button" className="btn-outline-premium flex items-center gap-2 px-8" onClick={onClose}>
            <X className="w-4 h-4" /> Close
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
}

// ── Login screen ──────────────────────────────────────────────────────────────

function LoginScreen() {
  const [name, setName] = useState("");
  const [role, setRole] = useState<"facilitator" | "commander">("facilitator");
  const login = useSynchroStore((s) => s.login);

  return (
    <div className="min-h-screen flex items-center justify-center p-6">
      <motion.div
        className="relative glass-card p-10 max-w-sm w-full text-center overflow-hidden"
        initial={{ opacity: 0, y: 24 }}
        animate={{ opacity: 1, y: 0 }}
      >
        {/* Gold shimmer top */}
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 3, background: "linear-gradient(90deg,transparent,#D4AF37,#F4E4A6,#D4AF37,transparent)" }} />

        <p className="font-mono text-[10px] font-bold tracking-[0.3em] uppercase text-gold mb-5">
          Xhosa Rise Global Holdings
        </p>

        <div className="w-16 h-16 rounded-2xl mx-auto mb-5 flex items-center justify-center text-3xl"
          style={{ background: "linear-gradient(135deg,rgba(212,175,55,.15),rgba(212,175,55,.05))", border: "1px solid rgba(212,175,55,.2)" }}>
          ⚖️
        </div>

        <h2 className="font-serif text-2xl font-bold mb-1"
          style={{ background: "linear-gradient(135deg,#F5F0E8,#F4E4A6)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>
          FINLIT SynchroLearn
        </h2>
        <p className="font-serif italic text-sm text-gold/80 mb-1">"Wamkelekile, Mhlonitshwa"</p>
        <p className="text-xs text-muted-foreground mb-7">SAPS Crime Prevention &amp; Financial Intelligence Portal</p>

        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && login(name.trim() || "Facilitator", role)}
          placeholder="Facilitator Name"
          className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm text-white placeholder:text-muted-foreground focus:outline-none focus:border-gold/40 mb-3"
        />

        <select
          value={role}
          onChange={(e) => setRole(e.target.value as "facilitator" | "commander")}
          title="Select your role"
          aria-label="Select your role"
          className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm text-white mb-5"
        >
          <option value="facilitator">👮 SAPS Facilitator</option>
          <option value="commander">🎖️ Provincial Commander</option>
        </select>

        <button
          type="button"
          className="btn-premium w-full flex items-center justify-center gap-2"
          onClick={() => login(name.trim() || "Facilitator", role)}
        >
          <Shield className="w-4 h-4" /> Access Secure Dashboard
        </button>

        <p className="font-mono text-[10px] text-muted-foreground mt-5 tracking-wider">
          Demo credentials: any name · offline capable · SAPS endorsed
        </p>
      </motion.div>
    </div>
  );
}

// ── Quiz component ────────────────────────────────────────────────────────────

interface ModuleQuizProps {
  offenderId: string;
  moduleIdx: number;
  quizTaken: boolean;
  score: number | null;
  onSubmit: (correctCount: number) => void;
  onRetake: () => void;
}

function ModuleQuiz({ offenderId, moduleIdx, quizTaken, score, onSubmit, onRetake }: ModuleQuizProps) {
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const questions = SYNCHRO_MODULES[moduleIdx].questions;

  if (quizTaken && score !== null && score < 3) {
    return (
      <div className="mt-3 p-4 rounded-xl" style={{ background: "rgba(192,57,43,.1)", border: "1px solid rgba(192,57,43,.3)" }}>
        <p className="font-serif text-lg font-bold mb-1" style={{ color: "#C0392B" }}>{score}/4</p>
        <p className="text-sm mb-3" style={{ color: "#C0392B" }}>Correct answers — need 3/4 to pass</p>
        <button type="button" className="btn-outline-premium text-xs px-4 py-1.5" onClick={onRetake}>
          🔄 Retake Quiz
        </button>
      </div>
    );
  }

  const allAnswered = questions.every((_, qi) => answers[qi] !== undefined);

  return (
    <div className="mt-4 space-y-5">
      {questions.map((q, qi) => (
        <div key={qi}>
          <p className="text-sm font-semibold text-white mb-2 pl-4 border-l-2 border-gold">
            {qi + 1}. {q.text}
          </p>
          <div className="space-y-2">
            {q.options.map((opt, oi) => (
              <label
                key={oi}
                className={`flex items-center gap-3 px-4 py-2.5 rounded-xl cursor-pointer transition-all text-sm border ${
                  answers[qi] === oi
                    ? "bg-gold/10 border-gold/40 text-gold"
                    : "bg-white/3 border-white/8 text-white/75 hover:bg-white/8 hover:border-white/20"
                }`}
                style={answers[qi] === oi ? {} : { background: "rgba(255,255,255,.03)", borderColor: "rgba(255,255,255,.08)" }}
              >
                <input
                  type="radio"
                  name={`q_${offenderId}_${moduleIdx}_${qi}`}
                  value={oi}
                  checked={answers[qi] === oi}
                  onChange={() => setAnswers((prev) => ({ ...prev, [qi]: oi }))}
                  className="sr-only"
                />
                {opt}
              </label>
            ))}
          </div>
        </div>
      ))}
      <button
        type="button"
        className="btn-premium w-full"
        onClick={() => {
          let c = 0;
          questions.forEach((q, qi) => { if (answers[qi] === q.correct) c++; });
          onSubmit(c);
        }}
        disabled={!allAnswered}
      >
        ✔ Submit Quiz
      </button>
    </div>
  );
}

// ── Module card ───────────────────────────────────────────────────────────────

interface ModuleCardProps {
  offenderId: string; moduleIdx: number; passed: boolean;
  trainingSeen: boolean; quizTaken: boolean; score: number | null;
  onMarkSeen: () => void;
  onSubmit: (c: number) => void;
  onRetake: () => void;
}

function ModuleCard({ offenderId, moduleIdx, passed, trainingSeen, quizTaken, score, onMarkSeen, onSubmit, onRetake }: ModuleCardProps) {
  const mod = SYNCHRO_MODULES[moduleIdx];
  const [open, setOpen] = useState(!passed);

  return (
    <div className="rounded-2xl overflow-hidden transition-all"
      style={{
        background: "linear-gradient(145deg,rgba(26,31,46,.9),rgba(18,22,32,.95))",
        border: passed ? "1px solid rgba(45,156,94,.3)" : "1px solid rgba(255,255,255,.06)",
        position: "relative",
      }}>
      {/* Left accent bar */}
      <div style={{
        position: "absolute", left: 0, top: 0, bottom: 0, width: 4,
        background: passed
          ? "linear-gradient(180deg,#2D9C5E,#0A4D3C)"
          : "linear-gradient(180deg,#D4AF37,#B8960C)",
        opacity: passed ? 1 : 0.5,
      }} />

      {/* Header toggle */}
      <button
        type="button"
        className="w-full pl-6 pr-5 py-5 flex items-center justify-between text-left"
        onClick={() => setOpen((o) => !o)}
      >
        <div className="flex items-center gap-3">
          {passed
            ? <CheckCircle className="w-5 h-5 shrink-0" style={{ color: "#2D9C5E" }} />
            : <BookOpen className="w-5 h-5 text-muted-foreground shrink-0" />
          }
          <div>
            <p className="text-sm font-semibold text-white">{mod.name}</p>
            <p className="text-[10px] text-muted-foreground mt-0.5 font-mono">📘 JSE: {mod.jse}</p>
          </div>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          {passed && <span className="text-xs font-bold" style={{ color: "#2D9C5E" }}>+20 pts</span>}
          {open ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />}
        </div>
      </button>

      {/* Body */}
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            key="body"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.22 }}
            className="overflow-hidden"
          >
            <div className="pl-6 pr-5 pb-5">
              <div className="rounded-xl p-4 text-sm leading-relaxed mb-3"
                style={{ background: "rgba(11,16,28,.6)", border: "1px solid rgba(255,255,255,.06)", color: "#A0A8B8" }}>
                {mod.training}
              </div>

              {passed ? (
                <div className="flex items-center gap-2 text-sm font-semibold" style={{ color: "#2D9C5E" }}>
                  <CheckCircle className="w-4 h-4" /> Module passed — 20 points earned
                </div>
              ) : !trainingSeen ? (
                <button type="button" className="btn-outline-premium text-xs px-4 py-2" onClick={onMarkSeen}>
                  📖 I have read the training
                </button>
              ) : (
                <ModuleQuiz
                  offenderId={offenderId}
                  moduleIdx={moduleIdx}
                  quizTaken={quizTaken}
                  score={score}
                  onSubmit={onSubmit}
                  onRetake={onRetake}
                />
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// ── Offender row ──────────────────────────────────────────────────────────────

interface OffenderRowProps {
  offender: OffenderRecord; isActive: boolean;
  onTrain: () => void; onIssueCert: () => void; onViewCert: () => void;
}

function OffenderRow({ offender, isActive, onTrain, onIssueCert, onViewCert }: OffenderRowProps) {
  const total = totalScore(offender.scores);
  const canCert = total >= 60 && !offender.certIssued;

  return (
    <motion.div
      layout
      className="rounded-2xl p-4 flex flex-wrap items-center justify-between gap-3 transition-all cursor-pointer"
      style={{
        background: isActive
          ? "linear-gradient(145deg,rgba(212,175,55,.08),rgba(26,31,46,.9))"
          : "linear-gradient(145deg,rgba(26,31,46,.8),rgba(18,22,32,.9))",
        border: isActive ? "1px solid #D4AF37" : "1px solid rgba(255,255,255,.06)",
        boxShadow: isActive ? "0 0 24px rgba(212,175,55,.08)" : "none",
        transform: isActive ? "translateX(4px)" : undefined,
      }}
      onClick={onTrain}
    >
      <div className="flex items-center gap-3 min-w-0">
        <div className="w-10 h-10 rounded-xl shrink-0 flex items-center justify-center font-serif font-bold text-sm"
          style={{ background: "linear-gradient(135deg,#B8960C,#D4AF37)", color: "#0D1117" }}>
          {offender.name.charAt(0)}
        </div>
        <div className="min-w-0">
          <p className="font-serif font-semibold text-white text-sm truncate">{offender.name}</p>
          <p className="font-mono text-[10px] text-gold">{offender.id}</p>
        </div>
      </div>

      {/* Progress */}
      <div className="flex items-center gap-3">
        <div>
          <div className="w-24 h-1.5 rounded-full overflow-hidden" style={{ background: "rgba(255,255,255,.06)" }}>
            <div className="h-full rounded-full transition-all" style={{ width: `${total}%`, background: "linear-gradient(90deg,#B8960C,#D4AF37)" }} />
          </div>
          <p className="font-mono text-[9px] text-muted-foreground mt-0.5 text-right">{total}/100</p>
        </div>
      </div>

      <div className="flex items-center gap-2 shrink-0" onClick={(e) => e.stopPropagation()}>
        {offender.certIssued && (
          <button type="button" onClick={onViewCert}
            className="flex items-center gap-1 px-2.5 py-1.5 rounded-xl text-xs font-semibold transition-all"
            style={{ background: "rgba(45,156,94,.1)", border: "1px solid rgba(45,156,94,.3)", color: "#2D9C5E" }}>
            <Award className="w-3 h-3" /> View Cert
          </button>
        )}
        {canCert && (
          <button type="button" onClick={onIssueCert}
            className="px-3 py-1.5 rounded-xl text-xs font-bold transition-all hover:-translate-y-0.5"
            style={{ background: "linear-gradient(135deg,#B8960C,#D4AF37)", color: "#0D1117", boxShadow: "0 2px 12px rgba(212,175,55,.2)" }}>
            🏆 Issue Cert
          </button>
        )}
        <button type="button" onClick={(e) => { e.stopPropagation(); onTrain(); }}
          className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all border ${
            isActive ? "bg-gold/20 border-gold/40 text-gold" : "bg-white/5 border-white/10 text-white hover:bg-white/10"
          }`}>
          🎯 Train
        </button>
      </div>
    </motion.div>
  );
}

// ── Facilitator guide ─────────────────────────────────────────────────────────

function FacilitatorGuide() {
  const [open, setOpen] = useState(false);
  const [done, setDone] = useState(false);

  return (
    <div className="glass-card p-5">
      <h4 className="font-semibold text-white mb-3 flex items-center gap-2">
        <ClipboardList className="w-4 h-4 text-gold" /> Facilitator Training (SAPS)
      </h4>
      <button type="button" className="btn-outline-premium w-full text-sm mb-2" onClick={() => setOpen((o) => !o)}>
        📘 {open ? "Hide" : "View"} Training Guide
      </button>
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden"
          >
            <div className="rounded-xl p-4 text-sm space-y-2 mt-2"
              style={{ background: "rgba(11,16,28,.6)", border: "1px solid rgba(255,255,255,.06)", color: "#A0A8B8" }}>
              <p className="font-semibold text-white">Facilitator Quick Guide</p>
              <p>• Each module: read training → click "I have read the training" → answer 4 questions → earn 20 pts if ≥3 correct.</p>
              <p>• Offenders need <strong className="text-gold/90">60+ points</strong> (3 modules) to qualify for a certificate.</p>
              <p>• Use the Parole Report to document progress for reintegration boards.</p>
              <p>• All data is stored offline — sync when internet is available.</p>
              <button type="button" className="btn-premium w-full mt-3" onClick={() => { setDone(true); setOpen(false); }}>
                {done ? "✅ Training Completed" : "✔ Mark Training as Completed"}
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// ── Dashboard ─────────────────────────────────────────────────────────────────

function SynchroDashboard() {
  const session     = useSynchroStore((s) => s.session)!;
  const offenders   = useSynchroStore((s) => s.offenders);
  const lastSync    = useSynchroStore((s) => s.lastSync);
  const logout      = useSynchroStore((s) => s.logout);
  const addOffender = useSynchroStore((s) => s.addOffender);
  const issueCert   = useSynchroStore((s) => s.issueCert);
  const markSeen    = useSynchroStore((s) => s.markTrainingSeen);
  const submitQuiz  = useSynchroStore((s) => s.submitQuiz);
  const resetQuiz   = useSynchroStore((s) => s.resetQuiz);
  const sync        = useSynchroStore((s) => s.sync);

  const { toasts, show: showToast } = useToasts();

  const [activeId, setActiveId]         = useState<string | null>(offenders[0]?.id ?? null);
  const [certData, setCertData]         = useState<CertData | null>(null);
  const [showConfetti, setShowConfetti] = useState(false);
  const [addName, setAddName]           = useState("");
  const [showAddInput, setShowAddInput] = useState(false);
  const [reportIdx, setReportIdx]       = useState(0);

  const activeOffender = offenders.find((o) => o.id === activeId) ?? null;

  const buildCertData = async (off: OffenderRecord): Promise<CertData> => {
    const hash = await sha256(`${off.id}:${off.name}:${totalScore(off.scores)}:${session.name}:${Date.now()}`);
    return {
      offender: off,
      hash,
      certId: hash.substring(0, 8).toUpperCase(),
      date: new Date().toLocaleDateString("en-ZA", { dateStyle: "long" }),
      facilitatorName: session.name,
    };
  };

  const handleIssueCert = async (id: string) => {
    const ok = issueCert(id);
    if (ok) {
      const off = offenders.find((o) => o.id === id)!;
      const data = await buildCertData(off);
      setCertData(data);
      setShowConfetti(true);
      showToast(`🎉 Certificate issued for ${off.name}!`, "success");
    } else {
      showToast("Requires at least 60 points (3 modules) to issue certificate.", "error");
    }
  };

  const handleViewCert = async (id: string) => {
    const off = offenders.find((o) => o.id === id)!;
    const data = await buildCertData(off);
    setCertData(data);
  };

  const handleAddOffender = () => {
    if (addName.trim()) {
      addOffender(addName.trim());
      setAddName(""); setShowAddInput(false);
      showToast(`Offender "${addName.trim()}" registered.`, "success");
    }
  };

  const totalMods = offenders.reduce((a, o) => a + o.scores.filter((s) => s === 20).length, 0);
  const totalCerts = offenders.filter((o) => o.certIssued).length;

  return (
    <div className="page-container pb-24">
      <ToastContainer toasts={toasts} />
      {showConfetti && <Confetti onDone={() => setShowConfetti(false)} />}

      {/* Header */}
      <div className="glass-card px-5 py-3 mb-6 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="rounded-xl px-4 py-2 flex items-center gap-2"
            style={{ background: "linear-gradient(135deg,rgba(212,175,55,.08),rgba(212,175,55,.02))", border: "1px solid rgba(212,175,55,.2)" }}>
            <Shield className="w-4 h-4 text-gold" />
            <div>
              <p className="font-mono text-[10px] font-bold text-gold uppercase tracking-widest">FINLIT | SAPS Social Crime Prevention</p>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-4 text-sm text-white/70">
          <div className="flex items-center gap-2 px-3 py-2 rounded-xl"
            style={{ background: "rgba(255,255,255,.03)", border: "1px solid rgba(255,255,255,.06)" }}>
            <div className="w-7 h-7 rounded-lg font-serif font-bold text-xs flex items-center justify-center"
              style={{ background: "linear-gradient(135deg,#B8960C,#D4AF37)", color: "#0D1117" }}>
              {session.name.charAt(0)}
            </div>
            <span>{session.role === "commander" ? "🎖️ Commander" : "👮 Facilitator"} · {session.name}</span>
          </div>
          <button type="button" onClick={logout}
            className="flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-xl transition-all hover:-translate-y-0.5"
            style={{ background: "rgba(192,57,43,.1)", border: "1px solid rgba(192,57,43,.2)", color: "#C0392B" }}>
            <LogOut className="w-3.5 h-3.5" /> Logout
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        {[
          { icon: Users, label: "Offenders Enrolled", value: offenders.length, trend: "+Active" },
          { icon: BookOpen, label: "Modules Completed",  value: totalMods,       trend: `${totalMods * 20} pts total` },
          { icon: Award,    label: "Certificates Issued", value: totalCerts,      trend: "Reintegration ready" },
        ].map(({ icon: Icon, label, value, trend }) => (
          <div key={label}
            className="relative overflow-hidden text-center rounded-2xl p-5 transition-all hover:-translate-y-1 cursor-default"
            style={{ background: "linear-gradient(145deg,rgba(22,27,34,.8),rgba(13,17,23,.9))", border: "1px solid rgba(255,255,255,.06)" }}>
            <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 2, background: "linear-gradient(90deg,transparent,rgba(212,175,55,.4),transparent)", opacity: 0 }} />
            <Icon className="w-5 h-5 text-gold mx-auto mb-2" />
            <p className="font-serif text-3xl font-black text-gold">{value}</p>
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider mt-1">{label}</p>
            <p className="font-mono text-[9px] mt-1" style={{ color: "#2D9C5E" }}>{trend}</p>
          </div>
        ))}
      </div>

      {/* Offender management */}
      <div className="glass-card p-5 mb-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="font-semibold text-white flex items-center gap-2">
              <Users className="w-4 h-4 text-gold" /> Offender Case Management
            </h3>
            <p className="text-xs text-muted-foreground mt-0.5">Click an offender to begin training</p>
          </div>
          <button type="button" onClick={() => setShowAddInput((v) => !v)}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all hover:-translate-y-0.5"
            style={{ background: "linear-gradient(135deg,#052E23,#1A6B52)", color: "white", boxShadow: "0 2px 12px rgba(26,107,82,.2)" }}>
            <UserPlus className="w-3.5 h-3.5" /> Register New
          </button>
        </div>

        <AnimatePresence>
          {showAddInput && (
            <motion.div
              initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }}
              className="overflow-hidden mb-4"
            >
              <div className="flex gap-2">
                <input type="text" value={addName} onChange={(e) => setAddName(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleAddOffender()}
                  placeholder="Enter offender full name"
                  className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-muted-foreground focus:outline-none focus:border-gold/40" />
                <button type="button" className="btn-premium px-5" onClick={handleAddOffender}>Add</button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="space-y-3">
          <AnimatePresence>
            {offenders.map((off) => (
              <OffenderRow
                key={off.id}
                offender={off}
                isActive={off.id === activeId}
                onTrain={() => setActiveId(off.id)}
                onIssueCert={() => handleIssueCert(off.id)}
                onViewCert={() => handleViewCert(off.id)}
              />
            ))}
          </AnimatePresence>
        </div>
      </div>

      {/* Module training */}
      <div className="glass-card p-5 mb-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold text-white flex items-center gap-2">
            <GraduationCap className="w-4 h-4 text-gold" /> SynchroLearn Modules
          </h3>
          <span className="text-xs font-semibold px-3 py-1.5 rounded-full"
            style={{ background: "rgba(212,175,55,.08)", border: "1px solid rgba(212,175,55,.2)", color: "#F4E4A6" }}>
            {activeOffender ? `👤 ${activeOffender.name}` : "Select an offender above"}
          </span>
        </div>

        {activeOffender ? (
          <div className="space-y-3">
            {SYNCHRO_MODULES.map((_, mi) => {
              const qs = activeOffender.quizState[String(mi)];
              return (
                <ModuleCard
                  key={mi}
                  offenderId={activeOffender.id}
                  moduleIdx={mi}
                  passed={activeOffender.scores[mi] === 20}
                  trainingSeen={qs?.trainingSeen ?? false}
                  quizTaken={qs?.quizTaken ?? false}
                  score={qs?.score ?? null}
                  onMarkSeen={() => markSeen(activeOffender.id, mi)}
                  onSubmit={(c) => {
                    submitQuiz(activeOffender.id, mi, c);
                    if (c >= 3) showToast(`✅ Module ${mi + 1} passed! +20 points`, "success");
                    else showToast(`Module ${mi + 1}: ${c}/4 correct — try again`, "error");
                  }}
                  onRetake={() => resetQuiz(activeOffender.id, mi)}
                />
              );
            })}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground text-center py-8">
            Click <strong className="text-white">🎯 Train</strong> on an offender above to load their modules.
          </p>
        )}
      </div>

      {/* Action cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Parole report */}
        <div className="glass-card p-5 transition-all hover:-translate-y-1">
          <h4 className="font-serif font-bold text-white mb-3 flex items-center gap-2 text-lg">
            <FileText className="w-4 h-4 text-gold" /> Parole Report
          </h4>
          <select value={reportIdx} onChange={(e) => setReportIdx(Number(e.target.value))}
            title="Select offender for report"
            aria-label="Select offender for report"
            className="w-full bg-white/5 border border-white/10 rounded-xl px-3 py-2.5 text-sm text-white mb-3">
            {offenders.map((o, i) => (
              <option key={o.id} value={i}>{o.name} ({totalScore(o.scores)} pts)</option>
            ))}
          </select>
          <button type="button" className="btn-premium w-full text-sm"
            onClick={() => openParoleReport(offenders[reportIdx], session.name)}>
            Generate PDF Report
          </button>
        </div>

        {/* Offline sync */}
        <div className="glass-card p-5 transition-all hover:-translate-y-1">
          <h4 className="font-serif font-bold text-white mb-3 flex items-center gap-2 text-lg">
            <RefreshCw className="w-4 h-4 text-gold" /> Offline Sync
          </h4>
          <div className="flex items-center gap-2 text-xs text-muted-foreground mb-3">
            <div className="w-2 h-2 rounded-full" style={{ background: "#2D9C5E", animation: "pulse 2s infinite" }} />
            Last sync: {lastSync ? new Date(lastSync).toLocaleTimeString("en-ZA") : "Never"}
          </div>
          <button type="button" className="btn-outline-premium w-full text-sm mb-2"
            onClick={() => { sync(); showToast("Offline sync completed.", "success"); }}>
            Sync Now
          </button>
          <p className="text-[10px] text-muted-foreground">✅ All data stored locally — works without internet</p>
        </div>

        {/* Facilitator guide */}
        <FacilitatorGuide />
      </div>

      {/* Certificate modal */}
      <AnimatePresence>
        {certData && <CertificateModal data={certData} onClose={() => setCertData(null)} />}
      </AnimatePresence>
    </div>
  );
}

// ── Default export ────────────────────────────────────────────────────────────

export default function SynchroLearn() {
  const session = useSynchroStore((s) => s.session);
  return session ? <SynchroDashboard /> : <LoginScreen />;
}
