import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  GraduationCap, Shield, Users, BookOpen, Award, RefreshCw,
  CheckCircle, UserPlus, LogOut, FileText, ChevronDown, ChevronUp,
  ClipboardList,
} from "lucide-react";
import {
  useSynchroStore, totalScore,
  type OffenderRecord,
} from "@/shared/stores/synchroStore";
import { SYNCHRO_MODULES } from "@/features/synchrolearn/data/modules";

// ── Helpers ───────────────────────────────────────────────────────────────────

function openParoleReport(off: OffenderRecord, facilitatorName: string) {
  const total = totalScore(off.scores);
  const completed = off.scores.filter((s) => s === 20).length;
  const html = `<!DOCTYPE html><html><head><title>Parole Report – ${off.name}</title>
<style>
  body{font-family:Georgia,serif;padding:48px;background:#fff8e7;color:#1a2a3a;max-width:720px;margin:0 auto;}
  h2{color:#1a3a6a;border-bottom:2px solid #c8a800;padding-bottom:8px;margin-bottom:20px;}
  .badge{display:inline-block;background:#1a3a6a;color:#fff;padding:3px 10px;border-radius:20px;font-size:.8rem;}
  .hl{color:#0055a5;font-weight:700;}
  p{margin:8px 0;line-height:1.6;}
  hr{border:none;border-top:1px solid #ccc;margin:24px 0;}
  .footer{font-size:.75rem;color:#777;margin-top:32px;}
  @media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact;}}
</style></head><body>
<h2>FINLIT SynchroLearn — Parole &amp; Reintegration Report</h2>
<p><strong>Offender:</strong> ${off.name} <span class="badge">${off.id}</span></p>
<p><strong>Total Score:</strong> <span class="hl">${total}/100</span> &nbsp;|&nbsp;
   <strong>Modules Completed:</strong> <span class="hl">${completed}/5</span></p>
<p><strong>Certificate Issued:</strong> ${off.certIssued ? '<span style="color:#1a7a3a">YES ✅</span>' : 'NO'}</p>
<p><strong>Facilitator:</strong> ${facilitatorName}</p>
<p><strong>Date:</strong> ${new Date().toLocaleDateString('en-ZA', { dateStyle: 'long' })}</p>
<hr>
<p>✅ This offender has demonstrated understanding of crime prevention, financial literacy, and JSE market principles through the FINLIT SynchroLearn programme.</p>
<p>Recommended for reintegration and parole consideration based on demonstrated financial literacy and commitment to legal wealth-building pathways.</p>
<div class="footer">Generated by FINLIT SynchroLearn — SAPS Social Crime Prevention Programme</div>
</body></html>`;
  const win = window.open("", "_blank", "width=800,height=620");
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 400);
  }
}

// ── Login screen ──────────────────────────────────────────────────────────────

function LoginScreen() {
  const [name, setName] = useState("");
  const [role, setRole] = useState<"facilitator" | "commander">("facilitator");
  const login = useSynchroStore((s) => s.login);

  return (
    <div className="min-h-screen flex items-center justify-center p-6">
      <motion.div
        className="glass-card p-10 max-w-sm w-full text-center"
        initial={{ opacity: 0, y: 24 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="text-5xl mb-4">⚖️🎮</div>
        <h2 className="font-serif text-2xl font-bold text-white mb-1">FINLIT SynchroLearn</h2>
        <p className="text-xs text-muted-foreground mb-6">
          SAPS Crime Prevention &amp; Financial Intelligence Portal
        </p>

        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Facilitator Name"
          className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm text-white placeholder:text-muted-foreground focus:outline-none focus:border-gold/40 mb-3"
        />

        <select
          value={role}
          onChange={(e) => setRole(e.target.value as "facilitator" | "commander")}
          className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm text-white mb-4"
        >
          <option value="facilitator">👮 SAPS Facilitator</option>
          <option value="commander">🎖️ Provincial Commander</option>
        </select>

        <button
          type="button"
          className="btn-premium w-full flex items-center justify-center gap-2"
          onClick={() => login(name.trim() || "Facilitator", role)}
        >
          <Shield className="w-4 h-4" /> Access Secure Dashboard
        </button>

        <p className="text-[10px] text-muted-foreground mt-4">
          Demo credentials: any name · offline capable · SAPS endorsed
        </p>
      </motion.div>
    </div>
  );
}

// ── Quiz for one module ───────────────────────────────────────────────────────

interface ModuleQuizProps {
  offenderId: string;
  moduleIdx: number;
  quizTaken: boolean;
  score: number | null;
  onSubmit: (correctCount: number) => void;
  onRetake: () => void;
}

function ModuleQuiz({ offenderId, moduleIdx, quizTaken, score, onSubmit, onRetake }: ModuleQuizProps) {
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const questions = SYNCHRO_MODULES[moduleIdx].questions;

  if (quizTaken && score !== null && score < 3) {
    return (
      <div className="mt-3 p-4 bg-xhosa-red/10 border border-xhosa-red/20 rounded-xl">
        <p className="text-sm text-xhosa-red font-medium mb-2">
          📊 Result: {score}/4 correct — Failed (need 3/4 to pass)
        </p>
        <button type="button" className="btn-outline-premium text-xs px-4 py-1.5" onClick={onRetake}>
          🔄 Retake Quiz
        </button>
      </div>
    );
  }

  const allAnswered = questions.every((_, qi) => answers[qi] !== undefined);

  const handleSubmit = () => {
    let correct = 0;
    questions.forEach((q, qi) => { if (answers[qi] === q.correct) correct++; });
    onSubmit(correct);
  };

  return (
    <div className="mt-3 space-y-5">
      {questions.map((q, qi) => (
        <div key={qi}>
          <p className="text-sm font-medium text-white mb-2">{qi + 1}. {q.text}</p>
          <div className="space-y-2">
            {q.options.map((opt, oi) => (
              <label
                key={oi}
                className={`flex items-center gap-3 px-4 py-2.5 rounded-xl cursor-pointer transition-all text-sm border ${
                  answers[qi] === oi
                    ? "bg-gold/15 border-gold/30 text-gold"
                    : "bg-white/5 border-white/10 text-white/80 hover:bg-white/10"
                }`}
              >
                <input
                  type="radio"
                  name={`q_${offenderId}_${moduleIdx}_${qi}`}
                  value={oi}
                  checked={answers[qi] === oi}
                  onChange={() => setAnswers((prev) => ({ ...prev, [qi]: oi }))}
                  className="sr-only"
                />
                {opt}
              </label>
            ))}
          </div>
        </div>
      ))}
      <button
        type="button"
        className="btn-premium w-full"
        onClick={handleSubmit}
        disabled={!allAnswered}
      >
        ✔ Submit Quiz
      </button>
    </div>
  );
}

// ── Single module card ────────────────────────────────────────────────────────

interface ModuleCardProps {
  offenderId: string;
  moduleIdx: number;
  passed: boolean;
  trainingSeen: boolean;
  quizTaken: boolean;
  score: number | null;
  onMarkSeen: () => void;
  onSubmit: (correctCount: number) => void;
  onRetake: () => void;
}

function ModuleCard({
  offenderId, moduleIdx, passed, trainingSeen, quizTaken, score,
  onMarkSeen, onSubmit, onRetake,
}: ModuleCardProps) {
  const mod = SYNCHRO_MODULES[moduleIdx];
  const [open, setOpen] = useState(!passed);

  return (
    <div className={`glass-card border-l-4 ${passed ? "border-l-xhosa-teal" : "border-l-white/10"}`}>
      {/* Header — always visible */}
      <button
        type="button"
        className="w-full p-5 flex items-center justify-between text-left"
        onClick={() => setOpen((o) => !o)}
      >
        <div className="flex items-center gap-3">
          {passed
            ? <CheckCircle className="w-5 h-5 text-xhosa-teal shrink-0" />
            : <BookOpen className="w-5 h-5 text-muted-foreground shrink-0" />
          }
          <div>
            <p className="text-sm font-semibold text-white">{mod.name}</p>
            <p className="text-[10px] text-muted-foreground mt-0.5">📘 JSE: {mod.jse}</p>
          </div>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          {passed && <span className="text-xs font-bold text-xhosa-teal">+20 pts</span>}
          {open ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />}
        </div>
      </button>

      {/* Expandable body */}
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            key="body"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.22 }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5">
              {/* Training text */}
              <div className="bg-white/5 rounded-xl p-4 text-sm text-white/80 leading-relaxed mb-3">
                {mod.training}
              </div>

              {passed ? (
                <div className="flex items-center gap-2 text-xhosa-teal text-sm font-medium">
                  <CheckCircle className="w-4 h-4" /> Module passed — 20 points earned
                </div>
              ) : !trainingSeen ? (
                <button type="button" className="btn-outline-premium text-xs px-4 py-2" onClick={onMarkSeen}>
                  📖 I have read the training
                </button>
              ) : (
                <ModuleQuiz
                  offenderId={offenderId}
                  moduleIdx={moduleIdx}
                  quizTaken={quizTaken}
                  score={score}
                  onSubmit={onSubmit}
                  onRetake={onRetake}
                />
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// ── Offender row ──────────────────────────────────────────────────────────────

interface OffenderRowProps {
  offender: OffenderRecord;
  isActive: boolean;
  onTrain: () => void;
  onIssueCert: () => void;
}

function OffenderRow({ offender, isActive, onTrain, onIssueCert }: OffenderRowProps) {
  const total = totalScore(offender.scores);
  const canCert = total >= 60 && !offender.certIssued;

  return (
    <motion.div
      layout
      className={`glass-card p-4 flex flex-wrap items-center justify-between gap-3 ${
        isActive ? "border border-gold/30" : ""
      }`}
    >
      <div className="flex items-center gap-3 min-w-0">
        <div className="w-9 h-9 rounded-xl bg-white/5 flex items-center justify-center shrink-0 text-sm font-bold text-muted-foreground">
          {offender.name.charAt(0)}
        </div>
        <div className="min-w-0">
          <p className="font-semibold text-white text-sm truncate">{offender.name}</p>
          <p className="text-[10px] text-muted-foreground">{offender.id} · {total}/100 pts</p>
        </div>
      </div>

      {/* Progress bar */}
      <div className="flex-1 min-w-[80px] max-w-[120px]">
        <div className="h-1.5 bg-white/10 rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-gold to-xhosa-teal rounded-full transition-all"
            style={{ width: `${total}%` }}
          />
        </div>
      </div>

      <div className="flex items-center gap-2 shrink-0">
        {offender.certIssued && (
          <span className="text-xs font-semibold text-xhosa-teal flex items-center gap-1">
            <Award className="w-3.5 h-3.5" /> Certified
          </span>
        )}
        {canCert && (
          <button
            type="button"
            onClick={onIssueCert}
            className="px-3 py-1.5 rounded-xl bg-gold/15 border border-gold/30 text-gold text-xs font-semibold hover:bg-gold/25 transition-all"
          >
            🏆 Issue Cert
          </button>
        )}
        <button
          type="button"
          onClick={onTrain}
          className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${
            isActive
              ? "bg-gold/20 border border-gold/40 text-gold"
              : "bg-white/5 border border-white/10 text-white hover:bg-white/10"
          }`}
        >
          🎯 Train
        </button>
      </div>
    </motion.div>
  );
}

// ── Facilitator guide ─────────────────────────────────────────────────────────

function FacilitatorGuide() {
  const [open, setOpen] = useState(false);
  const [done, setDone] = useState(false);

  return (
    <div className="glass-card p-5">
      <h4 className="font-semibold text-white mb-3 flex items-center gap-2">
        <ClipboardList className="w-4 h-4 text-gold" /> Facilitator Training (SAPS)
      </h4>
      <button type="button" className="btn-outline-premium w-full text-sm mb-2" onClick={() => setOpen((o) => !o)}>
        📘 {open ? "Hide" : "View"} Training Guide
      </button>
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden"
          >
            <div className="bg-white/5 rounded-xl p-4 text-sm text-white/80 space-y-2 mt-2">
              <p className="font-semibold text-white">Facilitator Quick Guide</p>
              <p>• Each module: read training → click "I have read the training" → answer 4 quiz questions → earn 20 points if ≥3 correct.</p>
              <p>• Offenders need <strong>60+ points</strong> (3 modules) to receive a certificate.</p>
              <p>• Use the Parole Report to document progress for reintegration.</p>
              <p>• All data is stored offline — sync when internet is available.</p>
              <button
                type="button"
                className="btn-premium w-full mt-3"
                onClick={() => { setDone(true); setOpen(false); }}
              >
                {done ? "✅ Training Completed" : "✔ Mark Training as Completed"}
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// ── Main dashboard ────────────────────────────────────────────────────────────

function SynchroDashboard() {
  const session      = useSynchroStore((s) => s.session)!;
  const offenders    = useSynchroStore((s) => s.offenders);
  const lastSync     = useSynchroStore((s) => s.lastSync);
  const logout       = useSynchroStore((s) => s.logout);
  const addOffender  = useSynchroStore((s) => s.addOffender);
  const issueCert    = useSynchroStore((s) => s.issueCert);
  const markSeen     = useSynchroStore((s) => s.markTrainingSeen);
  const submitQuiz   = useSynchroStore((s) => s.submitQuiz);
  const resetQuiz    = useSynchroStore((s) => s.resetQuiz);
  const sync         = useSynchroStore((s) => s.sync);

  const [activeId, setActiveId]         = useState<string | null>(offenders[0]?.id ?? null);
  const [certMessage, setCertMessage]   = useState<string | null>(null);
  const [reportIdx, setReportIdx]       = useState(0);
  const [addName, setAddName]           = useState("");
  const [showAddInput, setShowAddInput] = useState(false);

  const activeOffender = offenders.find((o) => o.id === activeId) ?? null;

  const totalOffenders   = offenders.length;
  const totalCompleted   = offenders.reduce((acc, o) => acc + o.scores.filter((s) => s === 20).length, 0);
  const totalCerts       = offenders.filter((o) => o.certIssued).length;

  const handleIssueCert = (id: string) => {
    const ok = issueCert(id);
    if (ok) {
      const off = offenders.find((o) => o.id === id);
      setCertMessage(`🎉 Certificate issued for ${off?.name}. Eligible for reintegration consideration.`);
      setTimeout(() => setCertMessage(null), 4000);
    } else {
      setCertMessage("Requires at least 60 points (3 modules completed).");
      setTimeout(() => setCertMessage(null), 3000);
    }
  };

  const handleAddOffender = () => {
    if (addName.trim()) {
      addOffender(addName.trim());
      setAddName("");
      setShowAddInput(false);
    }
  };

  return (
    <div className="page-container pb-24">
      {/* ── Header ──────────────────────────────────────────────────────── */}
      <div className="glass-card px-5 py-3 mb-6 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gold/10 border border-gold/20 flex items-center justify-center">
            <Shield className="w-4 h-4 text-gold" />
          </div>
          <div>
            <p className="text-xs font-semibold text-gold uppercase tracking-wider">FINLIT | SAPS Social Crime Prevention</p>
          </div>
        </div>
        <div className="flex items-center gap-4 text-sm text-white/70">
          <span>
            {session.role === "commander" ? "🎖️ Provincial Commander" : "👮 SAPS Facilitator"} · {session.name}
          </span>
          <button type="button" onClick={logout} className="flex items-center gap-1.5 text-xhosa-red hover:text-red-400 transition-colors text-xs">
            <LogOut className="w-3.5 h-3.5" /> Logout
          </button>
        </div>
      </div>

      {/* ── Cert celebration banner ──────────────────────────────────────── */}
      <AnimatePresence>
        {certMessage && (
          <motion.div
            initial={{ opacity: 0, y: -12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -12 }}
            className="glass-card px-5 py-3 mb-4 border border-gold/30 text-sm text-gold font-medium text-center"
          >
            {certMessage}
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Stats ───────────────────────────────────────────────────────── */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        {[
          { label: "Offenders Enrolled", value: totalOffenders, icon: Users },
          { label: "Modules Completed",  value: totalCompleted, icon: BookOpen },
          { label: "Certificates Issued", value: totalCerts,    icon: Award },
        ].map(({ label, value, icon: Icon }) => (
          <div key={label} className="glass-card p-4 text-center">
            <Icon className="w-4 h-4 text-gold mx-auto mb-1" />
            <p className="text-2xl font-black text-gold">{value}</p>
            <p className="text-[10px] text-muted-foreground leading-tight">{label}</p>
          </div>
        ))}
      </div>

      {/* ── Offender management ─────────────────────────────────────────── */}
      <div className="glass-card p-5 mb-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="font-semibold text-white flex items-center gap-2">
              <Users className="w-4 h-4 text-gold" /> Offender Case Management
            </h3>
            <p className="text-xs text-muted-foreground mt-0.5">Select an offender to begin training</p>
          </div>
          <button
            type="button"
            onClick={() => setShowAddInput((v) => !v)}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-white/5 border border-white/10 rounded-xl text-xs text-white hover:bg-white/10 transition-all"
          >
            <UserPlus className="w-3.5 h-3.5" /> Register
          </button>
        </div>

        {/* Add offender input */}
        <AnimatePresence>
          {showAddInput && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="overflow-hidden mb-4"
            >
              <div className="flex gap-2">
                <input
                  type="text"
                  value={addName}
                  onChange={(e) => setAddName(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleAddOffender()}
                  placeholder="Enter offender full name"
                  className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-muted-foreground focus:outline-none focus:border-gold/40"
                />
                <button type="button" className="btn-premium px-4" onClick={handleAddOffender}>Add</button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="space-y-3">
          <AnimatePresence>
            {offenders.map((off) => (
              <OffenderRow
                key={off.id}
                offender={off}
                isActive={off.id === activeId}
                onTrain={() => setActiveId(off.id)}
                onIssueCert={() => handleIssueCert(off.id)}
              />
            ))}
          </AnimatePresence>
        </div>
      </div>

      {/* ── Module training area ─────────────────────────────────────────── */}
      <div className="glass-card p-5 mb-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold text-white flex items-center gap-2">
            <GraduationCap className="w-4 h-4 text-gold" /> SynchroLearn Modules
          </h3>
          <span className="text-xs text-muted-foreground bg-white/5 px-3 py-1 rounded-full">
            {activeOffender ? `👤 ${activeOffender.name}` : "Select an offender above"}
          </span>
        </div>

        {activeOffender ? (
          <div className="space-y-3">
            {SYNCHRO_MODULES.map((_, mi) => {
              const qs = activeOffender.quizState[String(mi)];
              return (
                <ModuleCard
                  key={mi}
                  offenderId={activeOffender.id}
                  moduleIdx={mi}
                  passed={activeOffender.scores[mi] === 20}
                  trainingSeen={qs?.trainingSeen ?? false}
                  quizTaken={qs?.quizTaken ?? false}
                  score={qs?.score ?? null}
                  onMarkSeen={() => markSeen(activeOffender.id, mi)}
                  onSubmit={(count) => submitQuiz(activeOffender.id, mi, count)}
                  onRetake={() => resetQuiz(activeOffender.id, mi)}
                />
              );
            })}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground text-center py-8">
            Click <strong className="text-white">🎯 Train</strong> on an offender above to load their modules.
          </p>
        )}
      </div>

      {/* ── Action cards ────────────────────────────────────────────────── */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Parole report */}
        <div className="glass-card p-5">
          <h4 className="font-semibold text-white mb-3 flex items-center gap-2">
            <FileText className="w-4 h-4 text-gold" /> Parole &amp; Reintegration Report
          </h4>
          <select
            value={reportIdx}
            onChange={(e) => setReportIdx(Number(e.target.value))}
            className="w-full bg-white/5 border border-white/10 rounded-xl px-3 py-2.5 text-sm text-white mb-3"
          >
            {offenders.map((o, i) => (
              <option key={o.id} value={i}>
                {o.name} ({totalScore(o.scores)} pts)
              </option>
            ))}
          </select>
          <button
            type="button"
            className="btn-premium w-full text-sm"
            onClick={() => openParoleReport(offenders[reportIdx], session.name)}
          >
            Generate PDF Report
          </button>
        </div>

        {/* Offline sync */}
        <div className="glass-card p-5">
          <h4 className="font-semibold text-white mb-3 flex items-center gap-2">
            <RefreshCw className="w-4 h-4 text-gold" /> Offline Data Sync
          </h4>
          <p className="text-xs text-muted-foreground mb-1">Last synchronisation:</p>
          <p className="text-sm text-white mb-3">
            {lastSync ? new Date(lastSync).toLocaleTimeString("en-ZA") : "Never"}
          </p>
          <button
            type="button"
            className="btn-outline-premium w-full text-sm mb-2"
            onClick={sync}
          >
            Sync Now
          </button>
          <p className="text-[10px] text-muted-foreground">✅ All data stored locally — works without internet</p>
        </div>

        {/* Facilitator guide */}
        <FacilitatorGuide />
      </div>
    </div>
  );
}

// ── Page export ───────────────────────────────────────────────────────────────

export default function SynchroLearn() {
  const session = useSynchroStore((s) => s.session);
  return session ? <SynchroDashboard /> : <LoginScreen />;
}
